import 'package:flutter/material.dart';

class AppColors {
  static const pageBackground = Color(0xFFF4F4F4);
  static const backgroundSecondary = Color(0xFFF2F2F2);
  static const backgroundContent = Colors.white;
  static const background = Color(0xFFEFEFF0);
  static const textPrimaryBackground = Color(0xFFEFEFF0);
  static const disable = Color(0xFFB0B0B0);
  static const disableButton = Color(0xFFE2E2E2);
  static const disabledTextButton = Color(0xff757575);
  static const textPrimary = Colors.black;
  static const textSecondary = Color(0xFF747474);
  static const grey600 = Color(0xFF545454);
  static const hintText = Color(0xFFC2C2C2);
  static const textTertiary = Color(0xFFAAAAAA);
  static const textContrast = Colors.white;
  static const textLink = Color(0xFF2D81E0);
  static const cityText = Color(0xFF033E67);
  // static const primary = Color(0xFF7E49FF);
  static const negative = Color(0xFFE64646);
  static const positive = Color(0xFF2F8D32);
  static const lightGreen = Color(0xFFCBFFC5);
  static const primary = Color(0xFF00B505);
  static const neutral = Color(0x7FB4B4B4);
  static const adtimer = Color(0xFFFACC74);
  static const add = Color(0xFFFFFCE5);
  static const lotteryNeutral = Color(0xFFFFF9E6);
  static const game = Color(0xFFFFE3CE);
  static const city = Color(0xFFD0EBFE);
  static const charity = Color(0xFFDF656D);
  static const sale = Color(0xFFEB2121);
  static const border = Color(0xFFD9D9D9);
  static const transparentBlack = Color(0x54131313);
  static const switcherBackground = Color(0xFF333333);
  static const backBack = Color(0xffBFEB10);
  static const lightGreyIcon = Color(0xffCCCCCC);
  static Color blackOpacity = Colors.black.withOpacity(0.03999999910593033);
  static const transparentRed = Color(0xFFEDCECE);
  static const violetBlue = Color(0xff99a3ff);
  static const primaryPressedBackground = Color(0xFF681EE3);
  static const darkBlue = Color(0xFF1E45A2);
  static const purple100 = Color(0xFFECE8FF);
  // static const purpleBcg = Color(0xFFF5F2FF);
  static const purpleBcg = Color(0xFFF6F6F6);
  static const notificationRed = Color(0xFFFF3B30);
  static const red400 = Color(0xFFFF6C64);
  static const green600 = Color(0xff00B505);

  static const grey200 = Color(0xffE2E2E2);
  static const grey700 = Color(0xFF333333);
  static const grey500 = Color(0xff757575);
  static const backgroundGrey = Color(0xffeeeeee);
  static const purple600 = Color(0xFF7630F7);
  static const purple200 = Color(0xFFDAD4FF);
  static const purple400 = Color(0xFFA285FF);
  static const grey800 = Color(0xff1F1F1F);
    static const grey400 = Color(0xffAFAFAF);

}
